In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix
from qiskit_machine_learning.algorithms import QSVC, PegasosQSVC
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit.circuit.library import ZZFeatureMap
from qiskit_algorithms.utils import algorithm_globals
from multiprocessing import Process
import pandas as pd
import numpy as np
import os
from collections import Counter
import json

from custom_functions import print_result, getQAlgo, aggregate_pred, weighted_average
from custom_functions import read_df, save_to_file, print_arr, inc_prediction

In [2]:
data_dir = "datasets/balanced/"
model_dir = "inc_saved_models/"

# filename = "anysoftkeyboard"
# print(filename)

with open('datasets/balanced/ss_dict.json', 'r') as f:
    ss_dict = json.load(f)

In [3]:
list_predictions = []
for filename in ['facebook', 'kiwis', 'jm1', 'camel', 'os']: #'anysoftkeyboard', 
    #filename = "anysoftkeyboard"
    print(filename)
    testX, testY = read_df(data_dir + 'b_'+filename+'_test.csv')
    print(testX.shape, testY.shape, Counter(testY))

    y_filename = f'output/test_dump/{filename}_testY.txt'
    save_to_file(testY, y_filename)

    train_len = ss_dict[filename][0]
    cur_predictions = []
    x_st = 0
    for x_end in list(range(500, train_len, 500))+[train_len]:
        print(x_st, x_end)
        model_name = f"{filename}_{x_st}_{x_end}.model"
     
        print(f"Model: {model_name}")
        clf = QSVC.load(f"inc_saved_models/{model_name}") #Load QSVC 
        predict1D, runtime = inc_prediction(clf, testX)   
        cur_predictions.append(predict1D)
        print(f'file: {filename}, model: {model_name}, testing time: {runtime} seconds\n')

        print(confusion_matrix(testY, predict1D))
        print(print_result(testY, predict1D))

        outfilename = model_name.replace('.model', '')
        save_to_file(predict1D, f'output/test_dump/{outfilename}.txt')
        print("#=======================================")
        
    list_predictions.append(cur_predictions)
    print("#=================xxxxxxx======================")

facebook
(881, 6) (881,) Counter({1: 443, 0: 438})
0 500
Model: facebook_0_500.model


100%|██████████| 881/881 [17:49<00:00,  1.21s/it]


file: facebook, model: facebook_0_500.model, testing time: 1069.51 seconds

[[332 106]
 [ 67 376]]
[0.8, 0.78, 0.85, 0.81, 0.8, 0.61]
#=======================================
0 1000
Model: facebook_0_1000.model


100%|██████████| 881/881 [17:49<00:00,  1.21s/it]


file: facebook, model: facebook_0_1000.model, testing time: 1069.4 seconds

[[336 102]
 [104 339]]
[0.77, 0.77, 0.77, 0.77, 0.77, 0.53]
#=======================================
0 1500
Model: facebook_0_1500.model


100%|██████████| 881/881 [17:52<00:00,  1.22s/it]


file: facebook, model: facebook_0_1500.model, testing time: 1072.86 seconds

[[320 118]
 [ 88 355]]
[0.77, 0.75, 0.8, 0.78, 0.77, 0.53]
#=======================================
0 2000
Model: facebook_0_2000.model


100%|██████████| 881/881 [17:52<00:00,  1.22s/it]


file: facebook, model: facebook_0_2000.model, testing time: 1072.11 seconds

[[332 106]
 [ 81 362]]
[0.79, 0.77, 0.82, 0.79, 0.79, 0.58]
#=======================================
0 2500
Model: facebook_0_2500.model


100%|██████████| 881/881 [17:54<00:00,  1.22s/it]


file: facebook, model: facebook_0_2500.model, testing time: 1074.1 seconds

[[314 124]
 [ 72 371]]
[0.78, 0.75, 0.84, 0.79, 0.78, 0.56]
#=======================================
0 3000
Model: facebook_0_3000.model


100%|██████████| 881/881 [18:04<00:00,  1.23s/it]


file: facebook, model: facebook_0_3000.model, testing time: 1084.09 seconds

[[322 116]
 [ 82 361]]
[0.78, 0.76, 0.81, 0.78, 0.78, 0.55]
#=======================================
0 3500
Model: facebook_0_3500.model


100%|██████████| 881/881 [18:05<00:00,  1.23s/it]


file: facebook, model: facebook_0_3500.model, testing time: 1085.22 seconds

[[336 102]
 [101 342]]
[0.77, 0.77, 0.77, 0.77, 0.77, 0.54]
#=======================================
0 3523
Model: facebook_0_3523.model


100%|██████████| 881/881 [00:56<00:00, 15.59it/s]


file: facebook, model: facebook_0_3523.model, testing time: 56.51 seconds

[[118 320]
 [ 59 384]]
[0.57, 0.55, 0.87, 0.67, 0.57, 0.17]
#=======================================
#=================xxxxxxx======================
kiwis
(1227, 6) (1227,) Counter({0: 634, 1: 593})
0 500
Model: kiwis_0_500.model


100%|██████████| 1227/1227 [24:55<00:00,  1.22s/it]


file: kiwis, model: kiwis_0_500.model, testing time: 1495.7 seconds

[[438 196]
 [241 352]]
[0.64, 0.64, 0.59, 0.62, 0.64, 0.29]
#=======================================
0 1000
Model: kiwis_0_1000.model


100%|██████████| 1227/1227 [24:48<00:00,  1.21s/it]


file: kiwis, model: kiwis_0_1000.model, testing time: 1488.82 seconds

[[395 239]
 [203 390]]
[0.64, 0.62, 0.66, 0.64, 0.64, 0.28]
#=======================================
0 1500
Model: kiwis_0_1500.model


100%|██████████| 1227/1227 [24:55<00:00,  1.22s/it]


file: kiwis, model: kiwis_0_1500.model, testing time: 1495.57 seconds

[[416 218]
 [203 390]]
[0.66, 0.64, 0.66, 0.65, 0.66, 0.31]
#=======================================
0 2000
Model: kiwis_0_2000.model


100%|██████████| 1227/1227 [24:51<00:00,  1.22s/it]


file: kiwis, model: kiwis_0_2000.model, testing time: 1491.32 seconds

[[394 240]
 [204 389]]
[0.64, 0.62, 0.66, 0.64, 0.64, 0.28]
#=======================================
0 2500
Model: kiwis_0_2500.model


100%|██████████| 1227/1227 [24:43<00:00,  1.21s/it]


file: kiwis, model: kiwis_0_2500.model, testing time: 1483.7 seconds

[[409 225]
 [224 369]]
[0.63, 0.62, 0.62, 0.62, 0.63, 0.27]
#=======================================
0 3000
Model: kiwis_0_3000.model


100%|██████████| 1227/1227 [24:43<00:00,  1.21s/it]


file: kiwis, model: kiwis_0_3000.model, testing time: 1483.5 seconds

[[372 262]
 [200 393]]
[0.62, 0.6, 0.66, 0.63, 0.62, 0.25]
#=======================================
0 3500
Model: kiwis_0_3500.model


 28%|██▊       | 338/1227 [06:48<17:59,  1.21s/it]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

100%|██████████| 843/843 [1:20:46<00:00,  5.75s/it]


file: jm1, model: jm1_0_2500.model, testing time: 4846.06 seconds

[[178 235]
 [136 294]]
[0.56, 0.56, 0.68, 0.61, 0.56, 0.12]
#=======================================
0 3000
Model: jm1_0_3000.model


100%|██████████| 843/843 [1:21:08<00:00,  5.78s/it]


file: jm1, model: jm1_0_3000.model, testing time: 4868.34 seconds

[[304 109]
 [288 142]]
[0.53, 0.57, 0.33, 0.42, 0.53, 0.07]
#=======================================
0 3369
Model: jm1_0_3369.model


100%|██████████| 843/843 [59:56<00:00,  4.27s/it] 


file: jm1, model: jm1_0_3369.model, testing time: 3596.98 seconds

[[ 60 353]
 [ 45 385]]
[0.53, 0.52, 0.9, 0.66, 0.52, 0.06]
#=======================================
#=================xxxxxxx======================
camel
(400, 10) (400,) Counter({0: 200, 1: 200})
0 500
Model: camel_0_500.model


100%|██████████| 400/400 [34:13<00:00,  5.13s/it]


file: camel, model: camel_0_500.model, testing time: 2053.66 seconds

[[145  55]
 [ 27 173]]
[0.8, 0.76, 0.86, 0.81, 0.8, 0.6]
#=======================================
0 928
Model: camel_0_928.model


100%|██████████| 400/400 [29:55<00:00,  4.49s/it]


file: camel, model: camel_0_928.model, testing time: 1795.21 seconds

[[118  82]
 [ 21 179]]
[0.74, 0.69, 0.9, 0.78, 0.74, 0.51]
#=======================================
#=================xxxxxxx======================
os
(404, 10) (404,) Counter({1: 202, 0: 202})
0 500
Model: os_0_500.model


100%|██████████| 404/404 [26:48<00:00,  3.98s/it]


file: os, model: os_0_500.model, testing time: 1608.57 seconds

[[139  63]
 [ 99 103]]
[0.6, 0.62, 0.51, 0.56, 0.6, 0.2]
#=======================================
0 936
Model: os_0_936.model


100%|██████████| 404/404 [23:22<00:00,  3.47s/it]

file: os, model: os_0_936.model, testing time: 1402.66 seconds

[[106  96]
 [ 86 116]]
[0.55, 0.55, 0.57, 0.56, 0.55, 0.1]
#=======================================
#=================xxxxxxx======================


In [ ]:
#BREAK POINT!!!