In [1]:
import time
import pandas as pd
import numpy as np
from collections import Counter
# from qiskit_machine_learning.algorithms import PegasosQSVC, QSVC
# from qiskit_machine_learning.kernels import FidelityQuantumKernel
#from qiskit.circuit.library import ZFeatureMap
#from qiskit_algorithms.utils import algorithm_globals
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from custom_functions import print_result, getQAlgo, aggregate_pred, weighted_average, read_df, my_round, run_classical

In [2]:
#train_time testing_time accuracy, precision, recall, f1, roc_auc, mcc
# dataset_names = ['jm1', 'camel', 'os', 'bitcoin', 'qt', 'jenkins', 'litecoin',  'mongo', 'zxing', 
#                  'jackrabbit', 'oozie', 'tomcat', 'lucene', 'ambari', 'accumulo']

class_file_names = ['futile_abstract_pipeline', 'god_class', 'futile_hierarchy', 'model_class', 
                    'brain_class', 'data_class', 'schizofrenic_class']
method_file_names = ['shortcircuiting_method', 'brain_method', 'shotgun_surgery', 'extensive_coupling', 
                     'feature_envy', 'intensive_coupling']

# print(len(dataset_names), dataset_names[6:])

In [3]:
data_type = 'method'
data_dir = "../datasets/codesmell/"
for file in method_file_names:
    trainX, trainY = read_df(f"{data_dir}{data_type}_balanced/{file}_train.csv")
    print("train:", trainX.shape, Counter(trainY))
    
    testX, testY = read_df(f"{data_dir}{data_type}_balanced/{file}_test.csv")
    print("test:", testX.shape, Counter(testY))
    print()
    
    trainF = np.array(trainX, dtype='float')
    testF = np.array(testX, dtype='float')

    st = time.time()        
    # run_classical(getQAlgo('pqsvc'), 
    #           np.array(trainX, dtype='float'), 
    #           trainY, 
    #           np.array(testX, dtype='float'), 
    #           testY)
    run_classical(make_pipeline(StandardScaler(), SVC(gamma='auto')), trainF, trainY, testF, testY)
    et = time.time()
    print('{}: experiment time for dataset size {}: {} seconds'.format(file, len(trainX), round(et - st, 2)))
    print('----------------------------------')

train: (7452, 10) Counter({0: 3736, 1: 3716})
test: (3194, 10) Counter({1: 1607, 0: 1587})

Confusion Matrix:
 [[1537   50]
 [  29 1578]]
[0.98, 0.97, 0.98, 0.98, 0.98, 0.95]
shortcircuiting_method: experiment time for dataset size 7452: 0.7 seconds
----------------------------------
train: (21392, 10) Counter({0: 10747, 1: 10645})
test: (9168, 10) Counter({1: 4635, 0: 4533})

Confusion Matrix:
 [[4470   63]
 [   0 4635]]
[0.99, 0.99, 1.0, 0.99, 0.99, 0.99]
brain_method: experiment time for dataset size 21392: 1.21 seconds
----------------------------------
train: (27501, 10) Counter({1: 13759, 0: 13742})
test: (11787, 10) Counter({0: 5902, 1: 5885})

Confusion Matrix:
 [[5788  114]
 [  12 5873]]
[0.99, 0.98, 1.0, 0.99, 0.99, 0.98]
shotgun_surgery: experiment time for dataset size 27501: 3.43 seconds
----------------------------------
train: (4368, 10) Counter({1: 2191, 0: 2177})
test: (1872, 10) Counter({0: 943, 1: 929})

Confusion Matrix:
 [[933  10]
 [  0 929]]
[0.99, 0.99, 1.0, 0.9

In [ ]:
data_dir = "datasets/balanced/"
for filename in dataset_names:  
    print(filename)
    trainX, trainY = read_df(data_dir + 'b_'+filename+'_train.csv')
    testX, testY = read_df(data_dir + 'b_'+filename+'_test.csv')
    print(trainX.shape, trainY.shape, testX.shape, testY.shape)
    
    trainF = np.array(trainX, dtype='float')
    testF = np.array(testX, dtype='float')

    st = time.time()        
    # run_classical(getQAlgo('pqsvc'), 
    #           np.array(trainX, dtype='float'), 
    #           trainY, 
    #           np.array(testX, dtype='float'), 
    #           testY)
    run_classical(make_pipeline(StandardScaler(), SVC(gamma='auto')), trainF, trainY, testF, testY)
    et = time.time()
    print('{}: experiment time for dataset size {}: {} seconds'.format(filename, len(trainX), round(et - st, 2)))
    print('----------------------------------')

jm1
(3369, 10) (3369,) (843, 10) (843,)
Confusion Matrix:
 [[326  87]
 [199 231]]
[0.66, 0.73, 0.54, 0.62, 0.66, 0.34]
jm1: experiment time for dataset size 3369: 0.51 seconds
----------------------------------
camel
(928, 10) (928,) (400, 10) (400,)
Confusion Matrix:
 [[167  33]
 [ 36 164]]
[0.83, 0.83, 0.82, 0.83, 0.83, 0.66]
camel: experiment time for dataset size 928: 0.05 seconds
----------------------------------
os
(936, 10) (936,) (404, 10) (404,)
Confusion Matrix:
 [[100 102]
 [153  49]]
[0.37, 0.32, 0.24, 0.28, 0.37, -0.27]
os: experiment time for dataset size 936: 0.06 seconds
----------------------------------
bitcoin
(460, 10) (460,) (200, 10) (200,)
Confusion Matrix:
 [[85 15]
 [22 78]]
[0.81, 0.84, 0.78, 0.81, 0.82, 0.63]
bitcoin: experiment time for dataset size 460: 0.02 seconds
----------------------------------
qt
(472, 10) (472,) (204, 10) (204,)
Confusion Matrix:
 [[89 13]
 [50 52]]
[0.69, 0.8, 0.51, 0.62, 0.69, 0.41]
qt: experiment time for dataset size 472: 0.02 