In [1]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix
from qiskit_machine_learning.algorithms import QSVC, PegasosQSVC
from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit.circuit.library import ZZFeatureMap
from qiskit_algorithms.utils import algorithm_globals
from multiprocessing import Process
import pandas as pd
import numpy as np
import os
from collections import Counter
import json

from custom_functions import print_result, getQAlgo, aggregate_pred, weighted_average
from custom_functions import read_df, save_to_file, print_arr, inc_prediction

In [2]:
data_dir = "datasets/balanced/"
model_dir = "inc_saved_models/"
output_dir = "output/val_dump/"

with open('datasets/balanced/ss_dict.json', 'r') as f:
    ss_dict = json.load(f)

In [3]:
list_predictions = []
for filename in ['anysoftkeyboard', 'facebook', 'kiwis', 'jm1', 'camel', 'os']: #'anysoftkeyboard', 
    #filename = "anysoftkeyboard"
    print(filename)
    valX, valY = read_df(data_dir + 'b_'+filename+'_train.csv', sample_size=0.10) #Take 10% of the whole training dataset
    print(valX.shape, valY.shape, Counter(valY))

    y_filename = f'{output_dir}{filename}_valY.txt'
    save_to_file(valY, y_filename)

    train_len = ss_dict[filename][0]
    cur_predictions = []
    x_st = 0
    for x_end in list(range(500, train_len, 500))+[train_len]:
        print(x_st, x_end)
        model_name = f"{filename}_{x_st}_{x_end}.model"
     
        print(f"Model: {model_name}")
        clf = QSVC.load(f"inc_saved_models/{model_name}") #Load QSVC 
        predict1D, runtime = inc_prediction(clf, valX)   
        cur_predictions.append(predict1D)
        print(f'file: {filename}, model: {model_name}, testing time: {runtime} seconds\n')

        print(confusion_matrix(valY, predict1D))
        print(print_result(valY, predict1D))

        outfilename = model_name.replace('.model', '')
        save_to_file(predict1D, f'{output_dir}{outfilename}.txt')
        print("#=======================================")
        
    list_predictions.append(cur_predictions)
    print("#=================xxxxxxx======================")

anysoftkeyboard
(688, 6) (688,) Counter({1: 345, 0: 343})
0 500
Model: anysoftkeyboard_0_500.model


 99%|█████████▉| 680/688 [13:48<00:09,  1.22s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_500.model, testing time: 828.07 seconds

[[256  87]
 [153 192]]
[0.65, 0.69, 0.56, 0.62, 0.65, 0.31]
#=======================================
0 1000
Model: anysoftkeyboard_0_1000.model


 99%|█████████▉| 680/688 [13:49<00:09,  1.22s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_1000.model, testing time: 829.12 seconds

[[190 153]
 [105 240]]
[0.62, 0.61, 0.7, 0.65, 0.62, 0.25]
#=======================================
0 1500
Model: anysoftkeyboard_0_1500.model


 99%|█████████▉| 680/688 [14:12<00:10,  1.25s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_1500.model, testing time: 852.76 seconds

[[213 130]
 [107 238]]
[0.66, 0.65, 0.69, 0.67, 0.66, 0.31]
#=======================================
0 2000
Model: anysoftkeyboard_0_2000.model


 99%|█████████▉| 680/688 [14:32<00:10,  1.28s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_2000.model, testing time: 872.84 seconds

[[194 149]
 [124 221]]
[0.6, 0.6, 0.64, 0.62, 0.6, 0.21]
#=======================================
0 2500
Model: anysoftkeyboard_0_2500.model


 99%|█████████▉| 680/688 [15:03<00:10,  1.33s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_2500.model, testing time: 903.7 seconds

[[220 123]
 [134 211]]
[0.63, 0.63, 0.61, 0.62, 0.63, 0.25]
#=======================================
0 3000
Model: anysoftkeyboard_0_3000.model


 99%|█████████▉| 680/688 [14:13<00:10,  1.26s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_3000.model, testing time: 853.8 seconds

[[222 121]
 [144 201]]
[0.61, 0.62, 0.58, 0.6, 0.61, 0.23]
#=======================================
0 3500
Model: anysoftkeyboard_0_3500.model


 99%|█████████▉| 680/688 [14:12<00:10,  1.25s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_3500.model, testing time: 852.61 seconds

[[237 106]
 [134 211]]
[0.65, 0.67, 0.61, 0.64, 0.65, 0.3]
#=======================================
0 4000
Model: anysoftkeyboard_0_4000.model


 99%|█████████▉| 680/688 [14:03<00:09,  1.24s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_4000.model, testing time: 843.26 seconds

[[218 125]
 [128 217]]
[0.63, 0.63, 0.63, 0.63, 0.63, 0.26]
#=======================================
0 4500
Model: anysoftkeyboard_0_4500.model


 99%|█████████▉| 680/688 [14:08<00:09,  1.25s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_4500.model, testing time: 848.37 seconds

[[251  92]
 [161 184]]
[0.63, 0.67, 0.53, 0.59, 0.63, 0.27]
#=======================================
0 5000
Model: anysoftkeyboard_0_5000.model


 99%|█████████▉| 680/688 [14:06<00:09,  1.25s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_5000.model, testing time: 846.84 seconds

[[219 124]
 [124 221]]
[0.64, 0.64, 0.64, 0.64, 0.64, 0.28]
#=======================================
0 5500
Model: anysoftkeyboard_0_5500.model


 99%|█████████▉| 680/688 [13:56<00:09,  1.23s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_5500.model, testing time: 836.0 seconds

[[254  89]
 [150 195]]
[0.65, 0.69, 0.57, 0.62, 0.65, 0.31]
#=======================================
0 6000
Model: anysoftkeyboard_0_6000.model


 99%|█████████▉| 680/688 [14:14<00:10,  1.26s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_6000.model, testing time: 854.6 seconds

[[210 133]
 [118 227]]
[0.64, 0.63, 0.66, 0.64, 0.64, 0.27]
#=======================================
0 6500
Model: anysoftkeyboard_0_6500.model


 99%|█████████▉| 680/688 [14:40<00:10,  1.30s/it]


file: anysoftkeyboard, model: anysoftkeyboard_0_6500.model, testing time: 880.82 seconds

[[205 138]
 [103 242]]
[0.65, 0.64, 0.7, 0.67, 0.65, 0.3]
#=======================================
0 6883
Model: anysoftkeyboard_0_6883.model


 99%|█████████▉| 680/688 [10:38<00:07,  1.07it/s]


file: anysoftkeyboard, model: anysoftkeyboard_0_6883.model, testing time: 638.26 seconds

[[204 139]
 [122 223]]
[0.62, 0.62, 0.65, 0.63, 0.62, 0.24]
#=======================================
#=================xxxxxxx======================
facebook
(352, 6) (352,) Counter({0: 180, 1: 172})
0 500
Model: facebook_0_500.model


 99%|█████████▉| 350/352 [07:06<00:02,  1.22s/it]


file: facebook, model: facebook_0_500.model, testing time: 426.09 seconds

[[142  38]
 [ 28 144]]
[0.81, 0.79, 0.84, 0.81, 0.81, 0.63]
#=======================================
0 1000
Model: facebook_0_1000.model


 99%|█████████▉| 350/352 [07:07<00:02,  1.22s/it]


file: facebook, model: facebook_0_1000.model, testing time: 427.06 seconds

[[140  40]
 [ 29 143]]
[0.8, 0.78, 0.83, 0.81, 0.8, 0.61]
#=======================================
0 1500
Model: facebook_0_1500.model


 99%|█████████▉| 350/352 [07:06<00:02,  1.22s/it]


file: facebook, model: facebook_0_1500.model, testing time: 426.97 seconds

[[141  39]
 [ 30 142]]
[0.8, 0.78, 0.83, 0.8, 0.8, 0.61]
#=======================================
0 2000
Model: facebook_0_2000.model


 99%|█████████▉| 350/352 [07:07<00:02,  1.22s/it]


file: facebook, model: facebook_0_2000.model, testing time: 427.39 seconds

[[138  42]
 [ 20 152]]
[0.82, 0.78, 0.88, 0.83, 0.83, 0.65]
#=======================================
0 2500
Model: facebook_0_2500.model


 99%|█████████▉| 350/352 [07:07<00:02,  1.22s/it]


file: facebook, model: facebook_0_2500.model, testing time: 427.58 seconds

[[137  43]
 [ 24 148]]
[0.81, 0.77, 0.86, 0.82, 0.81, 0.62]
#=======================================
0 3000
Model: facebook_0_3000.model


 99%|█████████▉| 350/352 [07:07<00:02,  1.22s/it]


file: facebook, model: facebook_0_3000.model, testing time: 427.29 seconds

[[139  41]
 [ 28 144]]
[0.8, 0.78, 0.84, 0.81, 0.8, 0.61]
#=======================================
0 3500
Model: facebook_0_3500.model


 99%|█████████▉| 350/352 [07:06<00:02,  1.22s/it]


file: facebook, model: facebook_0_3500.model, testing time: 426.77 seconds

[[151  29]
 [ 40 132]]
[0.8, 0.82, 0.77, 0.79, 0.8, 0.61]
#=======================================
0 3523
Model: facebook_0_3523.model


 99%|█████████▉| 350/352 [00:22<00:00, 15.48it/s]


file: facebook, model: facebook_0_3523.model, testing time: 22.61 seconds

[[ 46 134]
 [ 22 150]]
[0.56, 0.53, 0.87, 0.66, 0.56, 0.16]
#=======================================
#=================xxxxxxx======================
kiwis
(490, 6) (490,) Counter({1: 248, 0: 242})
0 500
Model: kiwis_0_500.model


100%|██████████| 490/490 [09:49<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_500.model, testing time: 589.65 seconds

[[170  72]
 [113 135]]
[0.62, 0.65, 0.54, 0.59, 0.62, 0.25]
#=======================================
0 1000
Model: kiwis_0_1000.model


100%|██████████| 490/490 [09:47<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_1000.model, testing time: 587.36 seconds

[[161  81]
 [ 74 174]]
[0.68, 0.68, 0.7, 0.69, 0.68, 0.37]
#=======================================
0 1500
Model: kiwis_0_1500.model


100%|██████████| 490/490 [09:46<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_1500.model, testing time: 586.84 seconds

[[160  82]
 [ 91 157]]
[0.65, 0.66, 0.63, 0.64, 0.65, 0.29]
#=======================================
0 2000
Model: kiwis_0_2000.model


100%|██████████| 490/490 [09:47<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_2000.model, testing time: 587.73 seconds

[[139 103]
 [ 90 158]]
[0.61, 0.61, 0.64, 0.62, 0.61, 0.21]
#=======================================
0 2500
Model: kiwis_0_2500.model


100%|██████████| 490/490 [09:47<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_2500.model, testing time: 587.71 seconds

[[168  74]
 [ 98 150]]
[0.65, 0.67, 0.6, 0.64, 0.65, 0.3]
#=======================================
0 3000
Model: kiwis_0_3000.model


100%|██████████| 490/490 [09:46<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_3000.model, testing time: 586.82 seconds

[[158  84]
 [ 88 160]]
[0.65, 0.66, 0.65, 0.65, 0.65, 0.3]
#=======================================
0 3500
Model: kiwis_0_3500.model


100%|██████████| 490/490 [09:47<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_3500.model, testing time: 587.43 seconds

[[146  96]
 [ 89 159]]
[0.62, 0.62, 0.64, 0.63, 0.62, 0.24]
#=======================================
0 4000
Model: kiwis_0_4000.model


100%|██████████| 490/490 [09:47<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_4000.model, testing time: 587.76 seconds

[[166  76]
 [107 141]]
[0.63, 0.65, 0.57, 0.61, 0.63, 0.26]
#=======================================
0 4500
Model: kiwis_0_4500.model


100%|██████████| 490/490 [09:48<00:00,  1.20s/it]


file: kiwis, model: kiwis_0_4500.model, testing time: 588.1 seconds

[[178  64]
 [104 144]]
[0.66, 0.69, 0.58, 0.63, 0.66, 0.32]
#=======================================
0 4905
Model: kiwis_0_4905.model


100%|██████████| 490/490 [07:46<00:00,  1.05it/s]


file: kiwis, model: kiwis_0_4905.model, testing time: 466.46 seconds

[[166  76]
 [112 136]]
[0.62, 0.64, 0.55, 0.59, 0.62, 0.24]
#=======================================
#=================xxxxxxx======================
jm1
(337, 10) (337,) Counter({0: 170, 1: 167})
0 500
Model: jm1_0_500.model


 98%|█████████▊| 330/337 [32:33<00:41,  5.92s/it]


file: jm1, model: jm1_0_500.model, testing time: 1953.82 seconds

[[96 74]
 [70 97]]
[0.57, 0.57, 0.58, 0.57, 0.57, 0.15]
#=======================================
0 1000
Model: jm1_0_1000.model


 98%|█████████▊| 330/337 [32:15<00:41,  5.87s/it]


file: jm1, model: jm1_0_1000.model, testing time: 1935.84 seconds

[[145  25]
 [115  52]]
[0.58, 0.68, 0.31, 0.43, 0.58, 0.2]
#=======================================
0 1500
Model: jm1_0_1500.model


 98%|█████████▊| 330/337 [32:05<00:40,  5.83s/it]


file: jm1, model: jm1_0_1500.model, testing time: 1925.36 seconds

[[116  54]
 [ 88  79]]
[0.58, 0.59, 0.47, 0.53, 0.58, 0.16]
#=======================================
0 2000
Model: jm1_0_2000.model


 98%|█████████▊| 330/337 [32:01<00:40,  5.82s/it]


file: jm1, model: jm1_0_2000.model, testing time: 1921.7 seconds

[[ 67 103]
 [ 38 129]]
[0.58, 0.56, 0.77, 0.65, 0.58, 0.18]
#=======================================
0 2500
Model: jm1_0_2500.model


 98%|█████████▊| 330/337 [32:02<00:40,  5.82s/it]


file: jm1, model: jm1_0_2500.model, testing time: 1922.08 seconds

[[ 70 100]
 [ 51 116]]
[0.55, 0.54, 0.69, 0.61, 0.55, 0.11]
#=======================================
0 3000
Model: jm1_0_3000.model


 98%|█████████▊| 330/337 [32:07<00:40,  5.84s/it]


file: jm1, model: jm1_0_3000.model, testing time: 1927.34 seconds

[[138  32]
 [ 96  71]]
[0.62, 0.69, 0.43, 0.53, 0.62, 0.26]
#=======================================
0 3369
Model: jm1_0_3369.model


 98%|█████████▊| 330/337 [23:42<00:30,  4.31s/it]


file: jm1, model: jm1_0_3369.model, testing time: 1422.3 seconds

[[ 45 125]
 [ 16 151]]
[0.58, 0.55, 0.9, 0.68, 0.58, 0.22]
#=======================================
#=================xxxxxxx======================
camel
(93, 10) (93,) Counter({1: 48, 0: 45})
0 500
Model: camel_0_500.model


 97%|█████████▋| 90/93 [07:45<00:15,  5.18s/it]


file: camel, model: camel_0_500.model, testing time: 465.81 seconds

[[35 10]
 [ 6 42]]
[0.83, 0.81, 0.88, 0.84, 0.83, 0.66]
#=======================================
0 928
Model: camel_0_928.model


 97%|█████████▋| 90/93 [06:40<00:13,  4.45s/it]


file: camel, model: camel_0_928.model, testing time: 400.14 seconds

[[35 10]
 [ 5 43]]
[0.84, 0.81, 0.9, 0.85, 0.84, 0.68]
#=======================================
#=================xxxxxxx======================
os
(94, 10) (94,) Counter({0: 60, 1: 34})
0 500
Model: os_0_500.model


 96%|█████████▌| 90/94 [06:06<00:16,  4.07s/it]


file: os, model: os_0_500.model, testing time: 366.35 seconds

[[47 13]
 [ 3 31]]
[0.83, 0.7, 0.91, 0.79, 0.85, 0.67]
#=======================================
0 936
Model: os_0_936.model


 96%|█████████▌| 90/94 [05:18<00:14,  3.54s/it]

file: os, model: os_0_936.model, testing time: 318.19 seconds

[[44 16]
 [ 1 33]]
[0.82, 0.67, 0.97, 0.8, 0.85, 0.68]
#=======================================
#=================xxxxxxx======================


In [ ]:
filename = "anysoftkeyboard"
valX, valY = read_df(data_dir + 'b_'+filename+'_train.csv', sample_size=0.10) #Take 10% of the whole training dataset
print(valX.shape, valY.shape, Counter(valY))

y_filename = f'output/val_dump/{filename}_valY.txt'
save_to_file(valY, y_filename)

In [ ]:
#BREAK POINT!!!